### ISSUE TITLE
Docs and code inconsistency 

### ISSUE THREAD

**Issue by opensaucerer** [Vandathron/pub#1]
The docs states that logs are disabled by default. This would mean that the `DisableLogs` struct value be set to `true` by default when a call is made to the `NewPublisher()` function. 

However, this doesn't seem to be the case [here](https://github.com/Vandathron/pub/blob/f199ab1311ef6c224dda7e863db66a6c4f9d6952/pub.go#L18)

Great work on this... really cool stuff 🤓

**Comment by vandathron** [comment]
Thank you Sam!
